language: node_js

node_js:
  - "14"

branches:
  only:
    - master

#set notifications frequency
notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  #install rvm 2.6
  - rvm install 2.6
  #use rvm 2.6
  - rvm use 2.6
  #set home varaibles
  - . $HOME/.nvm/nvm.sh && nvm install 12.22.12 && nvm use 12.22.12
  # update gem
  - gem update --system
  #install gems through bundler
  - gem install bundler
  #if gems are missing this script will get the missing gems.
  - bundle check || bundle install

install:
  - skip

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
#  - nvm --version
  - nvm use v14.20.0
  - nvm ls
  - node --version
  - npm --version
  #install firebase tools, required to deploy on firebase hosting
  - npm install -g firebase-tools
  # precache
  - npm install --save-dev sw-precache
  #continue even after error
  - set -e
  #build jekyll site
  - JEKYLL_ENV=production jekyll build
  # precache
  - npm run precache

after_success:
  #deploy to firebase using stored token. 
  - firebase deploy --token $FIREBASE_TOKEN

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

#Visit article at - http://wrapcode.com
#Cheers, Rahul. 
